44 rewrite requests to xml
bratislava/ginis-sdk pull request #47
Opened 2024-12-18 13:01 UTC by lukasbabula

Existing endpoints moved from JSON to XML requests with underlying GINIS, including interface changes from JSON syntax (IdDokumentu) to XML syntax (Id-dokumentu) for all inputs and outputs.

3 failing tests:
- UDE endpoint Nacist-soubor - missing proper data on server for the test (the disk with the actual file has been damaged or removed)
- POD endpoint Detail-el-podani - POD services are not running currently on the test environment
- SSL endpoint Detai-dokumentu - responding 202 without data -> to be discussed about endpoint setup and management

2025-01-09 15:04 UTC, mpinter requested changes
Nice :+1:, gj, looking good, a few changes before we proceed though:
- see the comment, particularly the library change one
- let's also make the tests running before we proceed with this. I know they likely weren't in that state when we started and I remember the trouble we had making them so in the beginning, but now that we have the list of URLs which should work, let's make them green. That is, if for some of the test cases we still can't reach the server let's comment out for now and make them pass empty, and iterate on them as we receive new info/endpoints/solutions

2025-01-17 16:10 UTC, lukasbabula commented on src/api/xml/request-util.ts
> +  return JSON.parse(parser.toJson(responseXml))['s:Envelope']['s:Body'][`${requestName}Response`][`${requestName}Result`].Xrg
It does hold, it's the format defined for all the responses as far as I understand. And should there be a future exception, we can make it more robust later. But it holds for all the services we need.

2025-01-27 15:26 UTC, mpinter requested changes
Nice overall 🙌 

Suggestions mainly to typescript codestyle

2025-01-27 15:26 UTC, mpinter commented on src/api/xml/request-util.ts
> +export function createXmlRequestHeader(requestName: string, requestNamespace: string) {
this seems like needless indirection, would keep it all inside `createXmlRequestConfig` fn

2025-01-27 15:26 UTC, mpinter commented on src/api/xml/request-util.ts
> +  parseString(xml, options, (err, parsedResult) => {
use the promise variant - in general, aim for async/await (on promises) where you can avoid callbacks

2025-01-27 15:26 UTC, mpinter commented on src/api/xml/request-util.ts
> +function parseXml(xml: string, ignoreAttributes = true): any {
also seems like needless indirection - woudl rather use parseString directly, we use it in two places with different options, we don't really need to wrap it further

2025-01-27 15:26 UTC, mpinter commented on src/api/xml/request-util.ts
> +}
you can use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to simplify some of this, and probably rewrite the rest into something more concise - if you apply this and some of the other suggestions above, some of the error states might no longer "exist" (i.e. - if yu use parseString from the library directly, the returned values should never be undefined)

2025-01-29 08:46 UTC, lukasbabula commented on src/api/xml/gin/Detail-funkcniho-mista.ts
> +  [K in (typeof detailFunkcnihoMistaRequestProperties)[number] as K]?: string
For now all the input parameters are optional strings (regardless of their type or them actually being mandatory), only so we can keep them in an array and export the type directly for it. The array is necessary to keep the order of parameters required by the XML schema we must adhere to, and I wanted to avoid declaring all parameters in two separate places independently. I will try to find an elegant way to keep the parameters declared only in one place (probably the array) and still have the ability to set them optional and/or change their type.

2025-01-29 10:14 UTC, mpinter reviewed
More comments on writing ts in general 🙂 please check and let's discuss what applies.

As for the error parsign - I'd consider just printing the errors as the entire xmls everywhere, without trying to parse them into js objects and then returning a stringified part of that object, if it exists.

2025-01-29 10:14 UTC, mpinter commented on src/utils/request-util.ts
> +  } catch (ignored) {}
the other comment non-withstanding, this part throws and then immediately catches the error, likely just a typo/bug

2025-01-29 10:14 UTC, mpinter commented on src/utils/request-util.ts
> +}
will leave this to your call, but I'm not sure if parsing the error xml and reexporting part of it back as string is worth - I think we may have very little guarantees on the errors coming into this function in particular.

Moreover, this is only used in the 'debug' branch, which is intended to be used primarily by the developer on their machine as it already prints credentials / other data you may not want in your logs.

I'd consider just printing the errors as the entire xmls everywhere, without trying to parse them into js objects and then returning a stringified part of that object, if it exists.

2025-01-30 10:13 UTC, lukasbabula commented on src/api/xml/pod/__tests__/Detail-el-podani.test.ts
> +    expect(data?.['Detail-el-podani']?.['Id-dokumentu']).toBe('MAG0X03RYYSN')
clarifications:

2. it always throws
3. it is strictly defined int the endpoint how many records it returns and it is reflected in the Result attribute types (either as array, or as optional), but the main encapsulating object (Result, on xml side as Xrg) is only one in either case

2025-01-30 10:14 UTC, lukasbabula commented on src/api/xml/request-util.ts
> +  throwErrorFaultDetail(response, new Error(`Error parsing response data.`), false)
the main XML structure must be present in any case, everything else should be covered by the freshly implemented validation

2025-01-30 11:04 UTC, lukasbabula commented on src/api/xml/request-util.ts
> +  throwErrorFaultDetail(response, new Error(`Error parsing response data.`), false)
no longer applicable due to implemented result data validation

2025-01-30 11:14 UTC, lukasbabula commented on src/api/gin/Detail-referenta.ts
> +  'Alt-typ-autentizace-kod': z.string(),
Correct, I would like to have those constraints for all the parameters where ginis itself specifies constraints. However, it can (and will) change over-time, and it can break the library functionality. If they add value 50 to mean something our users don't care about - it will stop working until the constraint is implemented with us, and then our library version is upgraded on their end. If there are no explicit constrains, then if they don't need the new value (or don't even use that field at all) they don't have to care if it has new values and everything will continue working as before without any changes. 

I am split on this issue and it may require further discussion.

That said, I think it is outside the scope of this task/issue/PR and we can create a new one for this in particular after the discussion.

2025-01-30 11:16 UTC, lukasbabula commented on src/utils/request-util.ts
> +    throw new GinisError(`Failed to parse XML response${message}\r\nResponse: ${responseXml}`)
there shouldn't be any space before a colon

2025-01-30 13:03 UTC, lukasbabula commented on src/ginis.ts
> +  xml: {
Should this still be nested to point to the underlying structure needed for documentation of XML requests and responses or would it be better of unwrapped?

2025-01-30 13:31 UTC, mpinter requested changes
Would like to check the reponse typing mentioned in the comment below, and whether that can be nicer. Once that one is trough and you've checked the rest of the comments (nothing blocking in those), we can mvoe this forward :shipit:

2025-01-30 13:31 UTC, mpinter commented on src/utils/request-util.ts
> +): Promise<T> {
I do not think this is typed correctly, but again, I might be missing something

I'd expect that the inferred type this returns is the type that is validated by the responseSchema. I don't think that's what the function is returning now typewise

2025-01-30 13:31 UTC, mpinter commented on src/ginis.ts
> +  xml: {
you can unwrap

2025-01-30 13:44 UTC, lukasbabula commented on src/utils/request-util.ts
> +    throw new GinisError(`Failed to parse XML response${message}\r\nResponse: ${responseXml}`)
it was a bit hidden in the `message` variable as `': ${error.toString()}'`, but now it's gone anyway :)

2025-01-30 13:48 UTC, lukasbabula commented on src/utils/api.ts
> +    throw new GinisError('Axios POST failed with no ginis detail. This should never happen.')
I know, but TS doesn't. It is `Promise<never>` for this very reason, but awaiting such promise seems to be evaluated incorrectly. It thinks that the `responseAxios` might be unassigned since it doesn't understand that the `catch` always throws. It worked correctly without the promise, when the return type was only `never`.

2025-01-31 08:46 UTC, lukasbabula commented on src/utils/api.ts
> +    throw new GinisError('Axios POST failed with no ginis detail. This should never happen.')
Changed to returning the error from the function approach and throwing it explicitly after discussion.

2025-01-31 15:34 UTC, mpinter approved these changes
:+1: lgtm

after it's in master (and assuming the build works without issues), please publish a new version to npm as well, you should be able to do so using pipelines

2025-01-31 15:41 UTC, merged